<#
.SYNOPSIS
    Connection Objects Validation Check (REP-010)

.DESCRIPTION
    Validates NTDS Connection objects between domain controllers.
    Detects broken connections, orphaned objects, and topology issues.

.PARAMETER Inventory
    Discovered AD inventory object

.NOTES
    Check ID: REP-010
    Category: Replication
    Severity: High
    Compatible: Windows Server 2012 R2+
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [PSCustomObject]$Inventory
)

$ErrorActionPreference = 'Continue'
$results = @()

Write-Verbose "[REP-010] Starting connection objects validation check..."

try {
    $domains = $Inventory.Domains
    
    if (-not $domains) {
        Write-Warning "[REP-010] No domains found"
        return @()
    }
    
    foreach ($domain in $domains) {
        Write-Verbose "[REP-010] Checking connection objects for domain: $($domain.Name)"
        
        try {
            # Get all replication connections
            $connections = Get-ADReplicationConnection -Filter * -Server $domain.Name -ErrorAction Stop
            
            $totalConnections = $connections.Count
            $orphanedCount = 0
            $disabledCount = 0
            $manualCount = 0
            $autoCount = 0
            
            foreach ($conn in $connections) {
                # Check if connection is enabled
                if (-not $conn.ReplicateFromDirectoryServer) {
                    $disabledCount++
                }
                
                # Check if connection is manual or automatic
                if ($conn.AutoGenerated) {
                    $autoCount++
                }
                else {
                    $manualCount++
                }
                
                # Check if source DC exists
                try {
                    $sourceDN = $conn.ReplicateFromDirectoryServer
                    if ($sourceDN) {
                        $sourceObj = Get-ADObject -Identity $sourceDN -Server $domain.Name -ErrorAction SilentlyContinue
                        if (-not $sourceObj) {
                            $orphanedCount++
                        }
                    }
                }
                catch {
                    $orphanedCount++
                }
            }
            
            # Get DCs without connections
            $domainDCs = $Inventory.DomainControllers | 
                Where-Object { $_.Domain -eq $domain.Name }
            
            $dcsWithoutConnections = 0
            
            foreach ($dc in $domainDCs) {
                $dcConnections = $connections | Where-Object { 
                    $_.DistinguishedName -match "CN=$($dc.Name),"
                }
                
                if (-not $dcConnections -or $dcConnections.Count -eq 0) {
                    $dcsWithoutConnections++
                }
            }
            
            # Determine status
            $hasIssue = ($orphanedCount -gt 0 -or $dcsWithoutConnections -gt 0)
            $severity = if ($orphanedCount -gt 5 -or $dcsWithoutConnections -gt 1) { 'Critical' }
                       elseif ($orphanedCount -gt 0 -or $dcsWithoutConnections -gt 0) { 'High' }
                       elseif ($disabledCount -gt 3) { 'Medium' }
                       else { 'Info' }
            
            $result = [PSCustomObject]@{
                Domain = $domain.Name
                TotalConnections = $totalConnections
                AutoGeneratedConnections = $autoCount
                ManualConnections = $manualCount
                DisabledConnections = $disabledCount
                OrphanedConnections = $orphanedCount
                DCsWithoutConnections = $dcsWithoutConnections
                TotalDCs = $domainDCs.Count
                Severity = $severity
                Status = if ($orphanedCount -gt 5 -or $dcsWithoutConnections -gt 1) { 'Failed' }
                        elseif ($hasIssue) { 'Warning' }
                        else { 'Healthy' }
                IsHealthy = -not $hasIssue
                HasIssue = $hasIssue
                Message = if ($orphanedCount -gt 5) {
                    "CRITICAL: $orphanedCount orphaned connections! Topology broken!"
                }
                elseif ($dcsWithoutConnections -gt 1) {
                    "CRITICAL: $dcsWithoutConnections DCs have no replication connections!"
                }
                elseif ($orphanedCount -gt 0) {
                    "WARNING: $orphanedCount orphaned connections detected"
                }
                elseif ($dcsWithoutConnections -gt 0) {
                    "WARNING: $dcsWithoutConnections DC without connections"
                }
                else {
                    "All $totalConnections connection objects healthy"
                }
            }
            
            $results += $result
        }
        catch {
            Write-Warning "[REP-010] Failed to check connections for $($domain.Name): $_"
            
            $results += [PSCustomObject]@{
                Domain = $domain.Name
                TotalConnections = 0
                AutoGeneratedConnections = 0
                ManualConnections = 0
                DisabledConnections = 0
                OrphanedConnections = 0
                DCsWithoutConnections = 0
                TotalDCs = 0
                Severity = 'Error'
                Status = 'Error'
                IsHealthy = $false
                HasIssue = $true
                Message = "Failed to query connections: $_"
            }
        }
    }
    
    Write-Verbose "[REP-010] Check complete. Domains checked: $($results.Count)"
    
    return $results
}
catch {
    Write-Error "[REP-010] Check failed: $_"
    
    return @([PSCustomObject]@{
        Domain = "Unknown"
        TotalConnections = 0
        AutoGeneratedConnections = 0
        ManualConnections = 0
        DisabledConnections = 0
        OrphanedConnections = 0
        DCsWithoutConnections = 0
        TotalDCs = 0
        Severity = 'Error'
        Status = 'Error'
        IsHealthy = $false
        HasIssue = $true
        Message = "Check execution failed: $_"
    })
}
